require 'rake'

webdriver_dir = '../WebDriver'

task :webdriver_build do
    Dir.chdir( webdriver_dir ) do
        sh "./go common test_common"
    end
end

task :webdriver_java => [ :webdriver_build ] do
    require webdriver_dir + '/rake-tasks/task-gen' 
    require webdriver_dir + '/rake-tasks/checks' 
    require webdriver_dir + '/rake-tasks/zip' 
    require webdriver_dir + '/rake-tasks/java' 

    java_jar(:name => 'webdriver-hlwk',
             :deps => [ 'build/common/common.jar' ],
             :srcs => ["../driver/src/java/**/*.java"])

    extra_jars = []
    Dir.chdir( webdriver_dir ) do
        extra_jars = Dir.glob("common/lib/buildtime/*.jar")
    end
    java_test(:name => "webdriver-hlwk-test",
              :srcs  => [ "../driver/test/java/**/*.java" ],
              :deps =>  [ 'build/common/common.jar', 
                          'build/common/test.jar',
                          'third_party/java/junit/junit-dep-4.8.1.jar',
                          'webdriver-hlwk'] + extra_jars)
end

task :cd_webdriver do
    CurDir = Dir.getwd()
    puts "IN #{CurDir}"
    Dir.chdir( webdriver_dir )
    puts "NOW IN #{Dir.getwd()}"
end

task :cd_cur do
    Dir.chdir( CurDir )
end

task :setup_env do
  puts Dir.pwd;
  ENV['LD_LIBRARY_PATH'] = '../hlwk/WebKitBuild/Release'
end

task :webdriver => [ :webdriver_java, :cd_webdriver, 'webdriver-hlwk', :setup_env, 
                               'webdriver-hlwk-test', :cd_cur]
task :default => [:webdriver]
