require 'rake'

# Determine working folders
parent_dir = File.dirname(Dir.pwd)
webdriver_dir = parent_dir + '/WebDriver'
webkit_dir = parent_dir + '/driver'

# Change working directory to webdriver
Dir.chdir(webdriver_dir)

# Extra third_pary jars
third_party_jars_path = parent_dir + "/third_party/java/**/*.jar"
extra_third_party_jars = FileList.new(Dir.glob(third_party_jars_path))

# Extra webdriver jars
extra_jars_include = webdriver_dir + "/third_party/**/*.jar"
extra_jars_exclude = "android.jar"
extra_jars = FileList.new(Dir.glob(extra_jars_include)) do |f|
  f.exclude(extra_jars_exclude)
end

# Additional webdriver task definitions
require webdriver_dir + '/rake-tasks/task-gen' 
require webdriver_dir + '/rake-tasks/checks' 
require webdriver_dir + '/rake-tasks/zip' 
require webdriver_dir + '/rake-tasks/java' 

# Build webdriver and its tests
task :webdriver_build do
  sh "./go common test_common"
end



# Build webkitdriver
java_jar(:name => 'webdriver_hlwk',
         :deps => [:webdriver_build,
                   webdriver_dir + '/build/common/common.jar'] + extra_third_party_jars,
         :srcs => ["../driver/src/java/**/*.java"])

# Build webkitdriver tests
java_test(:name => "webdriver_hlwk_test",
          :srcs  => [ webkit_dir + '/test/java/**/*.java' ],
          :deps =>  [ :webdriver_hlwk,
                      webdriver_dir + '/build/common/test.jar',
                      webdriver_dir + '/build/common/common.jar'
                    ] + extra_jars)

# Helper task to cd to webdriver root
task :cd_webdriver do
    Dir.chdir(webdriver_dir)
end

# Helper task to cd to webkitdriver root
task :cd_webkit do
    Dir.chdir(webkit_dir)
end

# Setup environment variables
task :setup_env do
  puts Dir.pwd;
  ENV['LD_LIBRARY_PATH'] = parent_dir + '/hlwk/WebKitBuild/Release'
end

task :webkitdriver_build => [ 'webdriver_hlwk' ]

task :webkitdriver_test => [:webkitdriver_build, :setup_env, 'webdriver_hlwk_test']

task :default => [:webkitdriver_test]
